# Generated by Django 2.2.1 on 2019-10-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('date', models.DateTimeField()),
                ('num', models.CharField(max_length=128)),
            ],
        ),
    ]
