# Generated by Django 2.2.1 on 2019-10-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_auto_20191001_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='num',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
