# Generated by Django 2.2.1 on 2019-10-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_auto_20191001_1146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('name', 'date')},
        ),
    ]
